version: '3.8'

volumes:
  tike-tiko-pg-volume:

services:
  tike-tiko-pg:
    image: postgres:15
    container_name: tike-tiko-pg
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: tike_tiko
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itu16
    volumes:
      - tike-tiko-pg-volume:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tike_tiko" ]
      interval: 10s
      timeout: 5s
      retries: 5
